"use client";

import { motion } from "framer-motion";

import {
  Leaf,
  ShieldAlert,
  BrainCircuit,
  CalendarDays,
  Download,
} from "lucide-react";

interface Props {
  visible: boolean;
  reportRef?: React.RefObject<HTMLDivElement | null>;
}

export default function ReportDetails({
  visible,
  reportRef,
}: Props) {

  if (!visible) return null;

  return (

    <motion.section
  ref={reportRef}

      initial={{
        opacity: 0,
        y: 60,
      }}

      animate={{
        opacity: 1,
        y: 0,
      }}

      transition={{
        duration: .5,
      }}

      className="
        mt-10

        overflow-hidden

        rounded-[40px]

        border
        border-white/10

        bg-white/[0.04]

        backdrop-blur-3xl

        shadow-[0_35px_80px_rgba(0,0,0,.35)]
      "
    >

      {/* Header */}

      <div
        className="
          relative

          overflow-hidden

          border-b
          border-white/10

          px-10
          py-8
        "
      >

        <div
          className="
            absolute
            left-0
            top-0

            h-[240px]
            w-[240px]

            rounded-full

            bg-green-500/10

            blur-[120px]
          "
        />

        <div
          className="
            absolute
            right-0
            bottom-0

            h-[240px]
            w-[240px]

            rounded-full

            bg-cyan-500/10

            blur-[120px]
          "
        />

        <div className="relative flex items-center gap-5">

          <div
            className="
              rounded-2xl

              bg-green-500/10

              p-5
            "
          >

            <Leaf
              size={38}
              className="text-green-300"
            />

          </div>

          <div>

            <h2
              className="
                text-4xl
                font-black
                text-white
              "
            >
              AI Disease Report
            </h2>

            <p
              className="
                mt-2
                text-white/60
              "
            >
              Complete diagnosis generated by AgriSense AI
            </p>

          </div>

        </div>

      </div>
            {/* Content */}

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 p-10">

        {/* Left Side */}

        <div
          className="
            rounded-[32px]
            border
            border-white/10
            bg-white/[0.03]
            p-8
          "
        >

          <div
            className="
              h-[320px]
              w-full
              overflow-hidden
              rounded-[26px]
              border
              border-white/10
              bg-black/30
            "
          >

            <img
              src="/images/leaf-demo.jpg"
              alt="Leaf"
              className="
                h-full
                w-full
                object-cover
              "
            />

          </div>

          <div className="mt-8 space-y-5">

            <div className="flex justify-between">

              <span className="text-white/55">
                Crop
              </span>

              <span className="font-semibold text-white">
                Tomato
              </span>

            </div>

            <div className="flex justify-between">

              <span className="text-white/55">
                Disease
              </span>

              <span className="font-semibold text-red-300">
                Early Blight
              </span>

            </div>

            <div className="flex justify-between">

              <span className="text-white/55">
                Confidence
              </span>

              <span className="font-bold text-green-300">
                98.6%
              </span>

            </div>

            <div className="flex justify-between">

              <span className="text-white/55">
                Scan Date
              </span>

              <span className="text-white">
                30 Jul 2026
              </span>

            </div>

          </div>

        </div>

        {/* Right Side */}

        <div className="space-y-6">

          <div
            className="
              rounded-[28px]
              border
              border-white/10
              bg-white/[0.03]
              p-7
            "
          >

            <div className="flex items-center gap-3">

              <ShieldAlert
                className="text-red-300"
                size={24}
              />

              <h3
                className="
                  text-2xl
                  font-bold
                  text-white
                "
              >
                Disease Analysis
              </h3>

            </div>

            <p
              className="
                mt-5
                leading-8
                text-white/70
              "
            >
              Early Blight is a fungal disease commonly
              found in tomato plants. It spreads rapidly
              under humid conditions and affects leaves,
              stems and fruits, reducing crop yield if
              left untreated.
            </p>

          </div>

          <div
            className="
              rounded-[28px]
              border
              border-white/10
              bg-white/[0.03]
              p-7
            "
          >

            <div className="flex items-center gap-3">

              <BrainCircuit
                className="text-green-300"
                size={24}
              />

              <h3
                className="
                  text-2xl
                  font-bold
                  text-white
                "
              >
                AI Recommendation
              </h3>

            </div>

            <p
              className="
                mt-5
                leading-8
                text-white/70
              "
            >
              Apply Copper Oxychloride fungicide,
              remove infected leaves immediately,
              improve airflow between plants and avoid
              watering foliage during evening hours.
            </p>

          </div>
                    {/* Treatment */}

          <div
            className="
              rounded-[28px]
              border
              border-white/10
              bg-white/[0.03]
              p-7
            "
          >

            <div className="flex items-center gap-3">

              <CalendarDays
                className="text-cyan-300"
                size={24}
              />

              <h3
                className="
                  text-2xl
                  font-bold
                  text-white
                "
              >
                Prevention & Treatment
              </h3>

            </div>

            <ul
              className="
                mt-5
                space-y-4
                text-white/70
                leading-8
              "
            >

              <li>• Remove infected leaves immediately.</li>

              <li>• Improve air circulation.</li>

              <li>• Avoid overwatering the crop.</li>

              <li>• Apply Copper Oxychloride every 7 days.</li>

              <li>• Monitor surrounding plants regularly.</li>

            </ul>

          </div>

        </div>

      </div>

      {/* Footer */}

      <div
        className="
          flex
          items-center
          justify-between

          border-t
          border-white/10

          px-10
          py-7
        "
      >

        <div>

          <h4
            className="
              text-xl
              font-bold
              text-white
            "
          >
            AgriSense AI Diagnosis
          </h4>

          <p
            className="
              mt-2
              text-white/55
            "
          >
            AI generated crop disease analysis report.
          </p>

        </div>

        <button
          className="
            flex
            items-center
            gap-3

            rounded-2xl

            bg-gradient-to-r
            from-green-500
            to-emerald-600

            px-8
            py-4

            font-semibold
            text-white

            transition

            hover:scale-105

            shadow-[0_20px_45px_rgba(34,197,94,.35)]
          "
        >

          <Download size={20} />

          Download Report

        </button>

      </div>

    </motion.section>

  );

}